version: '3.8'

services:
  # 1. MySQL Database Container
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'ml_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. Python ML App Container
  app:
    build: .
    container_name: ml_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy